[package]
name = "file-transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
ctru-rs = { git = "https://github.com/Rust3DS/ctru-rs" }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
overflow-checks = false

[target.'cfg(target_os = "horizon")'.dependencies]
